### ISSUE TITLE
Config option request

### ISSUE THREAD

**Issue by breadguy69** [Anreol/ReleasedFromTheVoid#3]
would love the ability for the in lobby void coin modifier to be a config option instead of a lobby option to clear up the side panel and to avoid having to tick it on every time i restart the game. thank you!

**Comment by Anreol** [comment]
As of #5 I will keep that config and the new one as a rule that anybody can vote in the lobby, as its something that can be changed in the middle of the game with ease.
For other changes, like enemies, there's a new available config file for that, as that doesn't fit the run's rulebook
I recommend using https://thunderstore.io/package/KingEnderBrine/LobbyVotesSave/ or a server autoexecutable config file (Yes, those exist) to keep your votes between games.
