### ISSUE TITLE
Lunar equipment absent

### ISSUE THREAD

**Issue by JardonKern** [Anreol/ReleasedFromTheVoid#4]
There's mention of a new lunar equipment added by this mod, but it's nowhere to be found for me; every other feature works fine. Even if it's not supposed to have a logbook entry, I still doubt it's working as intended since I haven't come across it once during this past week.

**Comment by Anreol** [comment]
Will check it whenever I can, it actually is already in-game, but just set to be hidden, and my mod should absolutely set it to at the very least be dropable.

**Comment by Anreol** [comment]
![imagen](https://user-images.githubusercontent.com/12176932/163011355-49183cad-ee07-42a6-9024-9d08a9f15add.png)
Should be added for real in the next update.
If you wonder about the text, that's hopoo's.

**Comment by JardonKern** [comment]
Yeah, this latest update fixed it for me. I thought it'd be funny if hopoo really did write that, glad to know my suspicion was correct :)
