### ISSUE TITLE
[Suggestion] If possible, make Void Markers persistent

### ISSUE THREAD

**Issue by ArcaneTxsa** [Anreol/ReleasedFromTheVoid#5]
Just a suggestion for the Void Markers, as there's an option to make the void cradles cost a marker and they can appear in runs before you can actually acquire markers. An alternative could be to add a config option to start with some void markers to prevent cradles being unbuyable at the start of runs. 

Thanks for reading <3

**Comment by Anreol** [comment]
![imagen](https://user-images.githubusercontent.com/12176932/163015295-ec8805ee-0f93-45f8-9501-c8b615b0eb26.png)
Done
